modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "skinmc_mod"
version = "${version}"
displayName = "SkinMC Mod"
authors = "Rux"
description = '''
Wear your custom SkinMC cape in-game. Your style, your cape.
'''
logoFile = "assets/skinmc_mod/icon.png"

[[dependencies.skinmc_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skinmc_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skinmc_mod]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "skinmc_mod.mixins.json"
